export { default as Home } from "./Home/Home";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as Login } from "./Login/Login";
export { default as SignUp } from "./SignUp/SignUp";
export { default as Contact } from "./Contact/Contact";
export { default as Admin } from "./Admin/Admin";
export { default as AddProducts } from "./Admin/AddProduct/AddProducts";
export { default as NotFound } from "./404/404";
